### ISSUE TITLE
[Request] Menu with checkboxes

### ISSUE THREAD

**Issue by sleepylinde** [PrincessRTFM/AutoMountBGM#1]
Sorry if you don't take any requests, might as well delete this issue then.

I'd like to request a menu of some kind that is able to scan the mounts my character has, and where I can check on/off which mounts have their BGM enabled or not. I really like your idea of disabling the mount music on a case by case basis, but with my 193 mounts I dont wanna go through them all with only the option to type it.

Thank you for your consideration!

Edit: Or just a checkbox to turn off "Borderless" I cant really hear that song anymore lol

**Comment by PrincessRTFM** [comment]
It'd be practically trivial to list _every mount in the game_ in a window like that, but I need to find a way to check what mounts the current character has access to in order to make it filter like that.

I'll dig around in the game data and see if I can find an indicator that a given mount uses the Borderless bgm in order to at least disable the generic "you're using a mount" shit, too.

**Comment by sleepylinde** [comment]
Hell yeah!

The [better mount roulette plugin](https://github.com/CMDRNuffin/BetterMountRoulette) manages to grab the characters mounts, that might be worth looking into.

**Comment by PrincessRTFM** [comment]
From the look of things in that plugin, it's actually surprisingly simple to check if a mount is unlocked. Unfortunately, I'd need to query that every frame the list is drawn, for every mount in the game. It's... _probably_ fine, but it rankles. I'm toying with ways to avoid that right now.

**Comment by sleepylinde** [comment]
Thank you so much!
